### ISSUE TITLE
Show number on answer

### ISSUE THREAD

**Issue by guilherup** [aosg/cgr-web#3]
It would be helpful if the numbers were on the answer scale rather just a dot.

**Comment by DaviAragao** [comment]
Numbers per competency?
The numbers in questions are the order field in question object?
competency.question.order -> 1.
competency.question.name -> Carries a personal conviction of God’s calling to Adventist pastoral ministry

**Comment by guilherup** [comment]
It's about the score selector apperance when user are chosing or looking for the answer.
