### ISSUE TITLE
Deixa um para mim

### ISSUE THREAD

**Issue by DaviAragao** [aosg/cgr-web#9]

**Comment by guilherup** [comment]
Hehehehhe

**Comment by guilherup** [comment]
Slack: aosg.slack.com

**Comment by DaviAragao** [comment]
Não consegui logar no slack. Sorry, you entered an incorrect email address or password.

**Comment by DaviAragao** [comment]
:(

**Comment by DaviAragao** [comment]
Tentei usar os dois.
Da cpb: davi.aragao@cpb.com.br
Gmail: aragao.davi@gmail.com

**Comment by guilherup** [comment]
Mandei no aragao.davi@gmail.com

**Comment by guilherup** [comment]
Mandei agora o convite só.

**Comment by DaviAragao** [comment]
Aê!

**Comment by DaviAragao** [comment]
Internet da faculdade é muito ruim, não está abrindo o convite...

**Comment by guilherup** [comment]
De boa, vou dar um assign na issue que eu estiver trabalhando.
